name: currency_converter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+2

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  http: ^1.2.1
  fl_chart: ^0.68.0
  intl: ^0.17.0
  modal_bottom_sheet: ^3.0.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  rename: ^3.0.2
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.4
  build_runner: ^2.4.11

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  android: true
  ios: true
  color: "#170918"
  image: "assets/icon.png"

flutter:
  uses-material-design: true
